[benchmarks] F: Add cpu-bound benchmark
ppenna/nanvix pull request #331
Opened 2024-11-09 15:37 UTC by lemosep

Pull request regarding issue #330

2024-11-09 16:22 UTC, lemosep commented
During the check phase, when running the command `make -C src all` I've encountered a problem regarding the absence of the `BINARIES_DIR` variable on .[/src/libs/procd/Makefile](https://github.com/nanvix/nanvix/blob/3c9519eff78abf59e2d0d86698a2b25a3df3000e/src/libs/procd/Makefile) :
```makefile
...
#===============================================================================
# Directories
#===============================================================================

export ROOT_DIR  := $(CURDIR)
export BUILD_DIR := $(ROOT_DIR)/build
...


# Creates build directories.
make-dirs:
	@mkdir -p $(BINARIES_DIR) #<<<< variable later used here
``` 

So in order to procceed with the development of the remaining benchmarks, I will add this fix to this PR as well.

2024-11-11 20:58 UTC, ppenna commented
@lemosep CI is failing. Could you please fix it before I proceed with the review?

2024-11-11 22:22 UTC, ppenna commented
> During the check phase, when running the command `make -C src all` I've encountered a problem regarding the absence of the `BINARIES_DIR` variable on .[/src/libs/procd/Makefile](https://github.com/nanvix/nanvix/blob/3c9519eff78abf59e2d0d86698a2b25a3df3000e/src/libs/procd/Makefile) :
> 
> ```makefile
> ...
> #===============================================================================
> # Directories
> #===============================================================================
> 
> export ROOT_DIR  := $(CURDIR)
> export BUILD_DIR := $(ROOT_DIR)/build
> ...
> 
> 
> # Creates build directories.
> make-dirs:
> 	@mkdir -p $(BINARIES_DIR) #<<<< variable later used here
> ```
> 
> So in order to procceed with the development of the remaining benchmarks, I will add this fix to this PR as well.

Is this a problem or not? I am now confused.

2024-11-11 22:25 UTC, lemosep commented
Testing on my machine, the build fails on `procd`, but adding the `BINARIES_DIR` works out. I didn't expected the CI to work though.

2024-11-12 01:37 UTC, ppenna requested changes
I will consider this PR for review once we narrow down the requirements that we are putting together in https://github.com/nanvix/nanvix/issues/330.

2025-02-06 17:26 UTC, lemosep commented
@ppenna Closing this PR as this solution was designed in an old version of nanvix.

2025-02-06 20:14 UTC, closed without merging